import React, { useEffect, useState } from 'react';
import {
  View, Text, FlatList, TouchableOpacity, StyleSheet,
  Modal, ScrollView, TextInput, Alert, ActivityIndicator,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useReorders } from '../../hooks/useReorders';
import { useCompanySettings } from '../../hooks/useCompanySettings';
import { Reorder, ReorderItem, ReorderStatus } from '../../types';
import { Radius, Shadow } from '../../theme';
import { useAppTheme } from '../../context/ThemeContext';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

import * as FileSystem from 'expo-file-system/legacy';

const STATUS_COLORS: Record<string, string> = {
  Draft: '#888', Ordered: '#3B82F6',
  'Partially Received': '#F59E0B', Received: '#10B981',
};

const escapeHtml = (str: string) =>
  String(str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

const buildPdf = (order: Reorder, companyName: string) => {
  const rows = order.items.map((item, i) => `
    <tr>
      <td style="padding:10px 12px;border-bottom:1px solid #eeeeee">${i + 1}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #eeeeee"><strong>${escapeHtml(item.product_name)}</strong></td>
      <td style="padding:10px 12px;border-bottom:1px solid #eeeeee;color:#666666">${escapeHtml(item.sku || '—')}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #eeeeee">${escapeHtml(item.unit || 'unit')}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #eeeeee;color:#6C63FF;font-weight:bold">${item.reorder_quantity}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #eeeeee;color:#10B981;font-weight:bold">${item.received_quantity || 0}</td>
    </tr>`).join('');
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Purchase Order ${escapeHtml(order.order_number)}</title>
  <style>
    body { font-family: Helvetica, Arial, sans-serif; padding: 32px; color: #222222; font-size: 13px; line-height: 1.5; background-color: #ffffff; }
    h1 { font-size: 22px; font-weight: bold; color: #6C63FF; margin: 0 0 4px 0; }
    .meta { color: #666666; font-size: 12px; margin: 0 0 16px 0; }
    .vbox { background-color: #f5f4ff; border-left: 4px solid #6C63FF; padding: 12px 16px; border-radius: 4px; margin-bottom: 20px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th { background-color: #0F0F1A; color: #ffffff; padding: 10px 12px; text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }
    td { padding: 10px 12px; border-bottom: 1px solid #eeeeee; font-size: 13px; vertical-align: middle; }
    tr:last-child td { border-bottom: 2px solid #0F0F1A; }
    .foot { text-align: center; margin-top: 36px; font-size: 11px; color: #888888; border-top: 1px solid #eeeeee; padding-top: 16px; }
  </style>
</head>
<body>
  <h1>${escapeHtml(companyName)} — Purchase Order</h1>
  <p class="meta">#${escapeHtml(order.order_number)} &nbsp;|&nbsp; ${new Date(order.created_at).toLocaleDateString('en-IN', {day:'numeric',month:'long',year:'numeric'})} &nbsp;|&nbsp; Status: ${escapeHtml(order.status)}</p>
  <div class="vbox">
    <div style="font-size:10px;text-transform:uppercase;letter-spacing:1px;color:#6C63FF;font-weight:bold">Vendor</div>
    <div style="font-size:16px;font-weight:bold;color:#222222;margin-top:2px">${escapeHtml(order.vendor_name)}</div>
  </div>
  <table>
    <thead><tr><th>#</th><th>Product</th><th>SKU</th><th>Unit</th><th>Ordered</th><th>Received</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  ${order.total_paid > 0 ? `<p style="text-align:right;margin-top:16px;font-size:14px">Amount Paid: <strong>₹${order.total_paid.toLocaleString('en-IN')}</strong>${order.invoice_number ? ` &nbsp;|&nbsp; Invoice: ${escapeHtml(order.invoice_number)}` : ''}</p>` : ''}
  <div class="foot">Generated by ${escapeHtml(companyName)}</div>
</body>
</html>`;
};

// ─── Order Detail Modal ───────────────────────────────────────────────────────
interface DetailProps { order: Reorder; onClose: () => void; onRefresh: () => void; companyName: string; }

const OrderDetailModal: React.FC<DetailProps> = ({ order, onClose, onRefresh, companyName }) => {
  const { colors } = useAppTheme();
  const s = styles(colors);
  const { receiveReorder } = useReorders();

  const [receiveMode, setReceiveMode] = useState(false);
  const [step, setStep] = useState<'qty' | 'expense'>('qty');
  const [qtyMap, setQtyMap] = useState<Record<string, string>>(() => {
    const m: Record<string, string> = {};
    order.items.forEach(i => {
      m[i.product_id] = String(Math.max(0, i.reorder_quantity - (i.received_quantity || 0)));
    });
    return m;
  });
  const [totalPaid, setTotalPaid] = useState('');
  const [invoiceNum, setInvoiceNum] = useState('');
  const [purchaseDate, setPurchaseDate] = useState(new Date().toLocaleDateString('en-IN'));
  const [saving, setSaving] = useState(false);
  const [sharing, setSharing] = useState(false);
  const [viewing, setViewing] = useState(false);

  const canReceive = order.status === 'Ordered' || order.status === 'Partially Received';
  const sc = STATUS_COLORS[order.status] || '#888';

  const handleSharePDF = async () => {
    setSharing(true);
    try {
      const html = buildPdf(order, companyName);
      const { uri } = await Print.printToFileAsync({ html });

      const cleanNum = (order.order_number || 'order').replace(/[^a-zA-Z0-9_-]/g, '_');
      const targetUri = `${FileSystem.cacheDirectory}Purchase_Order_${cleanNum}.pdf`;

      await FileSystem.copyAsync({
        from: uri,
        to: targetUri,
      });

      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(targetUri, {
          mimeType: 'application/pdf',
          dialogTitle: `Purchase Order ${order.order_number}`,
          UTI: 'com.adobe.pdf',
        });
      } else {
        Alert.alert('Sharing Unavailable', 'Sharing is not available on this device.');
      }
    } catch (e: any) { Alert.alert('PDF Error', e.message || 'Failed to generate PDF'); }
    finally { setSharing(false); }
  };

  const handleViewPDF = async () => {
    setViewing(true);
    try {
      const html = buildPdf(order, companyName);
      await Print.printAsync({ html });
    } catch (e: any) { Alert.alert('PDF Error', e.message); }
    finally { setViewing(false); }
  };

  const handleSaveReceive = async () => {
    setSaving(true);
    try {
      const received = order.items.map(i => ({
        product_id: i.product_id,
        product_name: i.product_name,
        qty: parseInt(qtyMap[i.product_id] || '0', 10) || 0,
      }));
      await receiveReorder(order.id, received, parseFloat(totalPaid) || 0, invoiceNum.trim(), purchaseDate.trim());
      Alert.alert('Done!', 'Stock updated and reorder recorded.');
      onRefresh();
      onClose();
    } catch (e: any) { Alert.alert('Error', e.message); }
    finally { setSaving(false); }
  };

  return (
    <Modal visible animationType="slide" presentationStyle="pageSheet">
      <View style={s.modal}>
        {/* Header */}
        <View style={s.modalHeader}>
          <TouchableOpacity onPress={onClose} style={s.closeBtn}>
            <Ionicons name="close" size={22} color={colors.textPrimary} />
          </TouchableOpacity>
          <Text style={s.modalTitle}>#{order.order_number}</Text>
          <View style={{ flexDirection: 'row', gap: 8 }}>
            <TouchableOpacity onPress={handleViewPDF} style={s.shareBtnHeader} disabled={viewing}>
              {viewing ? <ActivityIndicator size="small" color={colors.primary} /> : <Ionicons name="eye-outline" size={20} color={colors.primary} />}
            </TouchableOpacity>
            <TouchableOpacity onPress={handleSharePDF} style={s.shareBtnHeader} disabled={sharing}>
              {sharing ? <ActivityIndicator size="small" color={colors.primary} /> : <Ionicons name="share-outline" size={20} color={colors.primary} />}
            </TouchableOpacity>
          </View>
        </View>

        <ScrollView contentContainerStyle={{ padding: 20 }}>
          {/* Status & vendor */}
          <View style={s.detailHero}>
            <View style={{ flex: 1 }}>
              <Text style={s.detailVendor}>{order.vendor_name}</Text>
              <Text style={s.detailDate}>{new Date(order.created_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</Text>
            </View>
            <View style={[s.statusBadge, { backgroundColor: sc + '20' }]}>
              <Text style={[s.statusText, { color: sc }]}>{order.status}</Text>
            </View>
          </View>

          {order.total_paid > 0 && (
            <View style={s.paidBanner}>
              <Ionicons name="checkmark-circle" size={16} color="#10B981" />
              <Text style={s.paidText}>Paid ₹{order.total_paid.toLocaleString('en-IN')}</Text>
              {order.invoice_number ? <Text style={s.paidInv}> • Inv #{order.invoice_number}</Text> : null}
            </View>
          )}

          {/* Items list */}
          <Text style={s.sectionLabel}>Items</Text>
          {order.items.map((item: ReorderItem) => {
            const rcvd = item.received_quantity || 0;
            const pct = item.reorder_quantity > 0 ? Math.min(1, rcvd / item.reorder_quantity) : 0;
            return (
              <View key={item.product_id} style={s.itemCard}>
                <View style={s.itemTop}>
                  <View style={{ flex: 1 }}>
                    <Text style={s.itemName}>{item.product_name}</Text>
                    <Text style={s.itemSku}>SKU: {item.sku || '—'} • {item.unit}</Text>
                  </View>
                  <View style={{ alignItems: 'flex-end' }}>
                    <Text style={s.itemOrdered}>{item.reorder_quantity} ordered</Text>
                    <Text style={[s.itemRcvd, { color: rcvd >= item.reorder_quantity ? '#10B981' : '#F59E0B' }]}>
                      {rcvd} received
                    </Text>
                  </View>
                </View>
                {/* Progress bar */}
                <View style={s.progressBg}>
                  <View style={[s.progressFill, { width: `${pct * 100}%` as any, backgroundColor: pct >= 1 ? '#10B981' : '#F59E0B' }]} />
                </View>
              </View>
            );
          })}

          {/* Receive block */}
          {canReceive && !receiveMode && (
            <TouchableOpacity style={s.receiveStartBtn} onPress={() => { setReceiveMode(true); setStep('qty'); }}>
              <Ionicons name="arrow-down-circle-outline" size={18} color="#fff" />
              <Text style={s.receiveStartText}>Receive Stock</Text>
            </TouchableOpacity>
          )}

          {receiveMode && step === 'qty' && (
            <View style={s.receiveBlock}>
              <Text style={s.receiveBlockTitle}>Enter Received Quantities</Text>
              {order.items.map((item: ReorderItem) => {
                const remaining = item.reorder_quantity - (item.received_quantity || 0);
                return (
                  <View key={item.product_id} style={s.receiveRow}>
                    <View style={{ flex: 1 }}>
                      <Text style={s.receiveItemName}>{item.product_name}</Text>
                      <Text style={s.receiveItemMeta}>Remaining: {remaining} {item.unit}</Text>
                    </View>
                    <View style={s.stepperRow}>
                      <TouchableOpacity style={s.stepBtn} onPress={() => {
                        const v = Math.max(0, (parseInt(qtyMap[item.product_id] || '0') || 0) - 1);
                        setQtyMap(p => ({ ...p, [item.product_id]: String(v) }));
                      }}>
                        <Ionicons name="remove" size={16} color={colors.textPrimary} />
                      </TouchableOpacity>
                      <TextInput
                        style={s.stepInput}
                        value={qtyMap[item.product_id]}
                        onChangeText={v => setQtyMap(p => ({ ...p, [item.product_id]: v }))}
                        keyboardType="number-pad"
                        placeholder="0"
                        placeholderTextColor={colors.textMuted}
                      />
                      <TouchableOpacity style={s.stepBtnFill} onPress={() => {
                        const v = (parseInt(qtyMap[item.product_id] || '0') || 0) + 1;
                        setQtyMap(p => ({ ...p, [item.product_id]: String(v) }));
                      }}>
                        <Ionicons name="add" size={16} color="#fff" />
                      </TouchableOpacity>
                    </View>
                  </View>
                );
              })}
              <View style={s.receiveActions}>
                <TouchableOpacity style={s.cancelReceiveBtn} onPress={() => setReceiveMode(false)}>
                  <Text style={s.cancelReceiveText}>Cancel</Text>
                </TouchableOpacity>
                <TouchableOpacity style={s.nextReceiveBtn} onPress={() => {
                  const anyQty = Object.values(qtyMap).some(v => parseInt(v) > 0);
                  if (!anyQty) { Alert.alert('Enter at least one received quantity'); return; }
                  setStep('expense');
                }}>
                  <Text style={s.nextReceiveText}>Next: Payment →</Text>
                </TouchableOpacity>
              </View>
            </View>
          )}

          {receiveMode && step === 'expense' && (
            <View style={s.receiveBlock}>
              <Text style={s.receiveBlockTitle}>Payment Details</Text>
              <Text style={s.fieldLabel}>Total Amount Paid (₹)</Text>
              <TextInput style={s.fieldInput} value={totalPaid} onChangeText={setTotalPaid} keyboardType="decimal-pad" placeholder="0.00" placeholderTextColor={colors.textMuted} autoFocus />
              <Text style={s.fieldLabel}>Invoice / Reference No. (optional)</Text>
              <TextInput style={s.fieldInput} value={invoiceNum} onChangeText={setInvoiceNum} placeholder="INV-001" placeholderTextColor={colors.textMuted} />
              <Text style={s.fieldLabel}>Date of Purchase</Text>
              <TextInput style={s.fieldInput} value={purchaseDate} onChangeText={setPurchaseDate} placeholder="DD/MM/YYYY" placeholderTextColor={colors.textMuted} />
              <View style={s.receiveActions}>
                <TouchableOpacity style={s.cancelReceiveBtn} onPress={() => setStep('qty')}>
                  <Text style={s.cancelReceiveText}>← Back</Text>
                </TouchableOpacity>
                <TouchableOpacity style={[s.nextReceiveBtn, { backgroundColor: '#10B981' }]} onPress={handleSaveReceive} disabled={saving}>
                  {saving ? <ActivityIndicator color="#fff" size="small" /> : <Text style={s.nextReceiveText}>Complete Receive</Text>}
                </TouchableOpacity>
              </View>
            </View>
          )}
        </ScrollView>
      </View>
    </Modal>
  );
};

// ─── History Tab ──────────────────────────────────────────────────────────────
export const ReorderHistoryTab: React.FC = () => {
  const { colors } = useAppTheme();
  const s = styles(colors);
  const { reorders, loading, fetch: fetchReorders, remove } = useReorders();
  const { settings: company, fetch: fetchCompany } = useCompanySettings();
  const [filterStatus, setFilterStatus] = useState<ReorderStatus | 'ALL'>('ALL');
  const [selectedOrder, setSelectedOrder] = useState<Reorder | null>(null);

  useEffect(() => { fetchReorders(true); fetchCompany(); }, []);

  const filtered = reorders.filter(r => filterStatus === 'ALL' || r.status === filterStatus);

  const handleDelete = (r: Reorder) => {
    Alert.alert('Delete Order', `Delete order #${r.order_number}?`, [
      { text: 'Cancel', style: 'cancel' },
      { text: 'Delete', style: 'destructive', onPress: () => remove(r.id) },
    ]);
  };

  const statuses: (ReorderStatus | 'ALL')[] = ['ALL', 'Ordered', 'Partially Received', 'Received', 'Draft'];

  return (
    <View style={{ flex: 1 }}>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} style={s.filterScroll} contentContainerStyle={{ gap: 8, paddingHorizontal: 16 }}>
        {statuses.map(st => (
          <TouchableOpacity key={st} style={[s.statusChip, filterStatus === st && s.statusChipActive]} onPress={() => setFilterStatus(st)}>
            <Text style={[s.statusChipText, filterStatus === st && s.statusChipTextActive]}>{st}</Text>
          </TouchableOpacity>
        ))}
      </ScrollView>

      <FlatList
        data={filtered}
        keyExtractor={r => r.id}
        refreshing={loading}
        onRefresh={() => fetchReorders(true)}
        contentContainerStyle={{ padding: 16, paddingBottom: 40 }}
        ListEmptyComponent={
          <View style={s.empty}>
            <Ionicons name="receipt-outline" size={48} color={colors.textMuted} />
            <Text style={s.emptyText}>No orders yet</Text>
          </View>
        }
        renderItem={({ item: r }) => {
          const sc = STATUS_COLORS[r.status] || '#888';
          const canReceive = r.status === 'Ordered' || r.status === 'Partially Received';
          const totalOrdered = r.items.reduce((s, i) => s + i.reorder_quantity, 0);
          const totalRcvd = r.items.reduce((s, i) => s + (i.received_quantity || 0), 0);
          return (
            <TouchableOpacity style={s.orderCard} onPress={() => setSelectedOrder(r)} activeOpacity={0.85}>
              <View style={s.orderTop}>
                <View style={{ flex: 1 }}>
                  <Text style={s.orderNum}>#{r.order_number}</Text>
                  <Text style={s.orderVendor}>{r.vendor_name}</Text>
                  <Text style={s.orderDate}>{new Date(r.created_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}</Text>
                </View>
                <View style={{ alignItems: 'flex-end', gap: 4 }}>
                  <View style={[s.statusBadge, { backgroundColor: sc + '20' }]}>
                    <Text style={[s.statusText, { color: sc }]}>{r.status}</Text>
                  </View>
                  <Text style={s.itemCount}>{r.items.length} item{r.items.length !== 1 ? 's' : ''}</Text>
                  {r.total_paid > 0 && <Text style={s.paidSmall}>Paid ₹{r.total_paid.toLocaleString('en-IN')}</Text>}
                </View>
              </View>

              {/* Progress */}
              <View style={s.progressRow}>
                <View style={s.progressBg}>
                  <View style={[s.progressFill, {
                    width: `${totalOrdered > 0 ? Math.min(100, (totalRcvd / totalOrdered) * 100) : 0}%` as any,
                    backgroundColor: totalRcvd >= totalOrdered ? '#10B981' : '#F59E0B',
                  }]} />
                </View>
                <Text style={s.progressText}>{totalRcvd}/{totalOrdered}</Text>
              </View>

              <View style={s.cardActions}>
                <TouchableOpacity style={s.detailBtn} onPress={() => setSelectedOrder(r)}>
                  <Ionicons name="eye-outline" size={14} color={colors.primary} />
                  <Text style={s.detailBtnText}>View Details</Text>
                </TouchableOpacity>
                {canReceive && (
                  <TouchableOpacity style={s.rcvBtn} onPress={() => setSelectedOrder(r)}>
                    <Ionicons name="arrow-down-circle-outline" size={14} color="#fff" />
                    <Text style={s.rcvBtnText}>Receive</Text>
                  </TouchableOpacity>
                )}
                <TouchableOpacity style={s.deleteBtn} onPress={() => handleDelete(r)}>
                  <Ionicons name="trash-outline" size={16} color="#EF4444" />
                </TouchableOpacity>
              </View>
            </TouchableOpacity>
          );
        }}
      />

      {selectedOrder && (
        <OrderDetailModal
          order={selectedOrder}
          companyName={company?.company_name || 'Company'}
          onClose={() => setSelectedOrder(null)}
          onRefresh={() => { fetchReorders(true); setSelectedOrder(null); }}
        />
      )}
    </View>
  );
};

const styles = (colors: any) => StyleSheet.create({
  filterScroll: { maxHeight: 50, paddingVertical: 8 },
  statusChip: { paddingHorizontal: 14, paddingVertical: 6, borderRadius: Radius.full, backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: colors.border },
  statusChipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  statusChipText: { fontSize: 12, fontWeight: '600', color: colors.textSecondary },
  statusChipTextActive: { color: '#fff' },
  orderCard: { backgroundColor: colors.surface, borderRadius: Radius.lg, padding: 16, marginBottom: 12, ...Shadow.sm },
  orderTop: { flexDirection: 'row', marginBottom: 10 },
  orderNum: { fontSize: 15, fontWeight: '800', color: colors.textPrimary },
  orderVendor: { fontSize: 13, color: colors.textSecondary, marginTop: 2 },
  orderDate: { fontSize: 11, color: colors.textMuted, marginTop: 2 },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: Radius.full },
  statusText: { fontSize: 11, fontWeight: '700' },
  itemCount: { fontSize: 11, color: colors.textMuted },
  paidSmall: { fontSize: 11, fontWeight: '700', color: '#10B981' },
  progressRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  progressBg: { flex: 1, height: 6, backgroundColor: colors.border, borderRadius: 3, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 3 },
  progressText: { fontSize: 11, color: colors.textMuted, fontWeight: '600', minWidth: 40, textAlign: 'right' },
  cardActions: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  detailBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, borderWidth: 1.5, borderColor: colors.primary, paddingVertical: 8, borderRadius: Radius.full },
  detailBtnText: { fontSize: 12, fontWeight: '700', color: colors.primary },
  rcvBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, backgroundColor: '#10B981', paddingVertical: 8, borderRadius: Radius.full },
  rcvBtnText: { fontSize: 12, fontWeight: '700', color: '#fff' },
  deleteBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: colors.surfaceAlt, alignItems: 'center', justifyContent: 'center' },
  empty: { alignItems: 'center', paddingTop: 60, gap: 10 },
  emptyText: { fontSize: 15, fontWeight: '600', color: colors.textMuted },
  // Modal
  modal: { flex: 1, backgroundColor: colors.background },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 20, borderBottomWidth: 1, borderColor: colors.border },
  closeBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: colors.surfaceAlt, alignItems: 'center', justifyContent: 'center' },
  shareBtnHeader: { width: 36, height: 36, borderRadius: 18, backgroundColor: colors.primary + '20', alignItems: 'center', justifyContent: 'center' },
  modalTitle: { fontSize: 17, fontWeight: '800', color: colors.textPrimary },
  detailHero: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 12 },
  detailVendor: { fontSize: 18, fontWeight: '800', color: colors.textPrimary },
  detailDate: { fontSize: 12, color: colors.textMuted, marginTop: 4 },
  paidBanner: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#10B98120', padding: 10, borderRadius: Radius.md, marginBottom: 12 },
  paidText: { fontSize: 13, fontWeight: '700', color: '#10B981' },
  paidInv: { fontSize: 12, color: '#10B981' },
  sectionLabel: { fontSize: 11, fontWeight: '700', color: colors.textSecondary, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 10, marginTop: 4 },
  itemCard: { backgroundColor: colors.surface, borderRadius: Radius.md, padding: 12, marginBottom: 8, ...Shadow.sm },
  itemTop: { flexDirection: 'row', marginBottom: 8 },
  itemName: { fontSize: 14, fontWeight: '700', color: colors.textPrimary },
  itemSku: { fontSize: 11, color: colors.textMuted, marginTop: 2 },
  itemOrdered: { fontSize: 12, color: colors.textSecondary, fontWeight: '600' },
  itemRcvd: { fontSize: 12, fontWeight: '700', marginTop: 2 },
  receiveStartBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: '#10B981', borderRadius: Radius.full, paddingVertical: 14, marginTop: 16 },
  receiveStartText: { fontSize: 15, fontWeight: '700', color: '#fff' },
  receiveBlock: { backgroundColor: colors.surface, borderRadius: Radius.lg, padding: 16, marginTop: 16, ...Shadow.sm },
  receiveBlockTitle: { fontSize: 16, fontWeight: '800', color: colors.textPrimary, marginBottom: 14 },
  receiveRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 10, borderBottomWidth: 1, borderColor: colors.border },
  receiveItemName: { fontSize: 13, fontWeight: '700', color: colors.textPrimary },
  receiveItemMeta: { fontSize: 11, color: colors.textMuted, marginTop: 2 },
  stepperRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  stepBtn: { width: 30, height: 30, borderRadius: 8, borderWidth: 1.5, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' },
  stepInput: { borderWidth: 1.5, borderColor: colors.primary, borderRadius: Radius.sm, paddingHorizontal: 8, paddingVertical: 5, fontSize: 15, fontWeight: '700', color: colors.textPrimary, minWidth: 50, textAlign: 'center' },
  stepBtnFill: { width: 30, height: 30, borderRadius: 8, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' },
  receiveActions: { flexDirection: 'row', gap: 10, marginTop: 14 },
  cancelReceiveBtn: { flex: 1, borderWidth: 1.5, borderColor: colors.border, borderRadius: Radius.full, paddingVertical: 11, alignItems: 'center' },
  cancelReceiveText: { fontSize: 13, fontWeight: '600', color: colors.textSecondary },
  nextReceiveBtn: { flex: 2, backgroundColor: colors.primary, borderRadius: Radius.full, paddingVertical: 11, alignItems: 'center' },
  nextReceiveText: { fontSize: 13, fontWeight: '700', color: '#fff' },
  fieldLabel: { fontSize: 11, fontWeight: '700', color: colors.textSecondary, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 8, marginTop: 14 },
  fieldInput: { backgroundColor: colors.surfaceAlt, borderRadius: Radius.md, paddingHorizontal: 14, paddingVertical: 11, fontSize: 15, color: colors.textPrimary, borderWidth: 1, borderColor: colors.border },
});
