import React, { useEffect, useState } from 'react';
import {
  View, Text, FlatList, TouchableOpacity, StyleSheet,
  TextInput, ScrollView, Alert, ActivityIndicator, Modal,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useProducts } from '../../hooks/useProducts';
import { useCompanySettings } from '../../hooks/useCompanySettings';
import { useReorders } from '../../hooks/useReorders';
import { Product, Reorder, ReorderItem } from '../../types';
import { Radius, Shadow } from '../../theme';
import { useAppTheme } from '../../context/ThemeContext';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';

type SelectedMap = Record<string, { qty: string }>;

const escapeHtml = (str: string) =>
  String(str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

const suggestedQty = (p: Product) =>
  Math.max(1, ((p.reorder_level ?? 5) * 2) - (p.stock_quantity ?? 0));

export const buildOrderPdfHtml = (order: Reorder, companyName: string) => {
  const rows = order.items.map((item, i) => `
    <tr>
      <td style="padding:10px 12px;border-bottom:1px solid #eeeeee">${i + 1}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #eeeeee"><strong>${escapeHtml(item.product_name)}</strong></td>
      <td style="padding:10px 12px;border-bottom:1px solid #eeeeee;color:#666666">${escapeHtml(item.sku || '—')}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #eeeeee">${escapeHtml(item.unit || 'unit')}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #eeeeee;font-size:15px;font-weight:bold;color:#6C63FF">${item.reorder_quantity}</td>
    </tr>`).join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Purchase Order ${escapeHtml(order.order_number)}</title>
  <style>
    body { font-family: Helvetica, Arial, sans-serif; padding: 32px; color: #222222; font-size: 13px; line-height: 1.5; background-color: #ffffff; }
    .header { border-bottom: 3px solid #6C63FF; padding-bottom: 16px; margin-bottom: 20px; }
    h1 { font-size: 22px; font-weight: bold; color: #6C63FF; margin: 0 0 4px 0; }
    .meta { font-size: 12px; color: #666666; margin: 0; }
    .vendor-box { background-color: #f5f4ff; border-left: 4px solid #6C63FF; padding: 12px 16px; border-radius: 4px; margin: 16px 0 24px 0; }
    .vendor-label { font-size: 10px; text-transform: uppercase; letter-spacing: 1px; color: #6C63FF; font-weight: bold; }
    .vendor-name { font-size: 16px; font-weight: bold; color: #222222; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th { background-color: #0F0F1A; color: #ffffff; padding: 10px 12px; text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }
    td { padding: 10px 12px; border-bottom: 1px solid #eeeeee; font-size: 13px; vertical-align: middle; }
    tr:last-child td { border-bottom: 2px solid #0F0F1A; }
    .footer { margin-top: 36px; text-align: center; font-size: 11px; color: #888888; border-top: 1px solid #eeeeee; padding-top: 16px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${escapeHtml(companyName)} — Purchase Order</h1>
    <p class="meta">Order #: <strong>${escapeHtml(order.order_number)}</strong> &nbsp;|&nbsp; Date: ${new Date(order.created_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
  </div>
  <div class="vendor-box">
    <div class="vendor-label">Vendor / Supplier</div>
    <div class="vendor-name">${escapeHtml(order.vendor_name)}</div>
  </div>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Product</th>
        <th>SKU / Code</th>
        <th>Unit</th>
        <th>Qty Required</th>
      </tr>
    </thead>
    <tbody>
      ${rows}
    </tbody>
  </table>
  <div class="footer">Generated by ${escapeHtml(companyName)} &nbsp;•&nbsp; ${new Date().toLocaleDateString('en-IN')}</div>
</body>
</html>`;
};

interface SuccessModalProps {
  orders: Reorder[];
  companyName: string;
  onDone: () => void;
}

const OrderSuccessModal: React.FC<SuccessModalProps> = ({ orders, companyName, onDone }) => {
  const { colors } = useAppTheme();
  const s = styles(colors);
  const [sharingId, setSharingId] = useState<string | null>(null);
  const [viewingId, setViewingId] = useState<string | null>(null);

  const handleShare = async (order: Reorder) => {
    setSharingId(order.id);
    try {
      const html = buildOrderPdfHtml(order, companyName);
      const { uri } = await Print.printToFileAsync({ html });
      
      const cleanNum = (order.order_number || 'order').replace(/[^a-zA-Z0-9_-]/g, '_');
      const targetUri = `${FileSystem.cacheDirectory}Purchase_Order_${cleanNum}.pdf`;

      await FileSystem.copyAsync({
        from: uri,
        to: targetUri,
      });

      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(targetUri, {
          mimeType: 'application/pdf',
          dialogTitle: `Purchase Order ${order.order_number}`,
          UTI: 'com.adobe.pdf',
        });
      } else {
        Alert.alert('Sharing Unavailable', 'Sharing is not available on this device.');
      }
    } catch (e: any) {
      Alert.alert('PDF Error', e.message || 'Failed to generate PDF');
    } finally {
      setSharingId(null);
    }
  };

  const handleView = async (order: Reorder) => {
    setViewingId(order.id);
    try {
      const html = buildOrderPdfHtml(order, companyName);
      await Print.printAsync({ html });
    } catch (e: any) {
      Alert.alert('PDF Error', e.message || 'Failed to preview PDF');
    } finally {
      setViewingId(null);
    }
  };

  return (
    <Modal visible animationType="slide" presentationStyle="pageSheet">
      <View style={s.successModal}>
        <View style={s.successTop}>
          <View style={s.successIcon}>
            <Ionicons name="checkmark-circle" size={52} color="#10B981" />
          </View>
          <Text style={s.successTitle}>Orders Placed!</Text>
          <Text style={s.successSubtitle}>
            {orders.length} order{orders.length !== 1 ? 's' : ''} created successfully
          </Text>
        </View>

        <ScrollView contentContainerStyle={s.successBody}>
          <Text style={s.successSectionLabel}>View or Share Order PDFs with vendors</Text>
          {orders.map(order => (
            <View key={order.id} style={s.orderPdfCard}>
              <View style={{ flex: 1 }}>
                <Text style={s.orderPdfNum}>#{order.order_number}</Text>
                <Text style={s.orderPdfVendor}>{order.vendor_name}</Text>
                <Text style={s.orderPdfItems}>{order.items.length} item{order.items.length !== 1 ? 's' : ''}</Text>
              </View>
              <View style={{ flexDirection: 'row', gap: 6 }}>
                <TouchableOpacity
                  style={[s.sharePdfBtn, { backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: colors.border }]}
                  onPress={() => handleView(order)}
                  disabled={viewingId === order.id}
                >
                  {viewingId === order.id ? (
                    <ActivityIndicator size="small" color={colors.primary} />
                  ) : (
                    <>
                      <Ionicons name="eye-outline" size={15} color={colors.primary} />
                      <Text style={[s.sharePdfBtnText, { color: colors.primary }]}>View</Text>
                    </>
                  )}
                </TouchableOpacity>
                <TouchableOpacity
                  style={s.sharePdfBtn}
                  onPress={() => handleShare(order)}
                  disabled={sharingId === order.id}
                >
                  {sharingId === order.id ? (
                    <ActivityIndicator size="small" color="#fff" />
                  ) : (
                    <>
                      <Ionicons name="share-outline" size={15} color="#fff" />
                      <Text style={s.sharePdfBtnText}>Share</Text>
                    </>
                  )}
                </TouchableOpacity>
              </View>
            </View>
          ))}
        </ScrollView>

        <View style={s.successFooter}>
          <TouchableOpacity style={s.doneBtn} onPress={onDone}>
            <Text style={s.doneBtnText}>View Orders & Receive →</Text>
          </TouchableOpacity>
        </View>
      </View>
    </Modal>
  );
};

interface Props {
  onOrderCreated: () => void;
}

export const ReorderCreateTab: React.FC<Props> = ({ onOrderCreated }) => {
  const { colors } = useAppTheme();
  const s = styles(colors);
  const { products, fetch: fetchProducts } = useProducts();
  const { settings: company, fetch: fetchCompany } = useCompanySettings();
  const { createReorder } = useReorders();

  const [selected, setSelected] = useState<SelectedMap>({});
  const [vendorFilter, setVendorFilter] = useState('ALL');
  const [showLowOnly, setShowLowOnly] = useState(false);
  const [saving, setSaving] = useState(false);
  const [createdOrders, setCreatedOrders] = useState<Reorder[]>([]);

  useEffect(() => { fetchProducts(); fetchCompany(); }, []);

  const getVendor = (p: Product) =>
    (p as any).vendor || (p.category ? p.category : 'No Vendor');

  const vendors = ['ALL', ...Array.from(new Set(products.map(getVendor)))];

  const filtered = products.filter(p => {
    if (showLowOnly) {
      if ((p.stock_quantity ?? 0) > (p.reorder_level ?? 5)) return false;
    }
    if (vendorFilter !== 'ALL' && getVendor(p) !== vendorFilter) return false;
    return true;
  });

  const toggle = (p: Product) => {
    setSelected(prev => {
      if (prev[p.id]) {
        const next = { ...prev };
        delete next[p.id];
        return next;
      }
      return { ...prev, [p.id]: { qty: String(suggestedQty(p)) } };
    });
  };

  const selectLowStock = () => {
    const next: SelectedMap = {};
    products.forEach(p => {
      if ((p.stock_quantity ?? 0) <= (p.reorder_level ?? 5)) {
        next[p.id] = { qty: String(suggestedQty(p)) };
      }
    });
    setSelected(next);
  };

  const selectedProducts = products.filter(p => !!selected[p.id]);

  const vendorGroups: Record<string, Product[]> = {};
  selectedProducts.forEach(p => {
    const v = getVendor(p);
    if (!vendorGroups[v]) vendorGroups[v] = [];
    vendorGroups[v].push(p);
  });

  const handlePlaceOrders = async () => {
    if (!selectedProducts.length) { Alert.alert('Select at least one product'); return; }
    setSaving(true);
    try {
      const newOrders: Reorder[] = [];
      for (const [vendorName, vProducts] of Object.entries(vendorGroups)) {
        const items: ReorderItem[] = vProducts.map(p => ({
          product_id: p.id,
          product_name: p.name,
          sku: p.sku,
          unit: p.unit,
          vendor: vendorName,
          reorder_quantity: parseInt(selected[p.id]?.qty || '0', 10) || 0,
          received_quantity: 0,
        }));
        const order = await createReorder(vendorName, items);
        if (order) newOrders.push(order);
      }
      setSelected({});
      setCreatedOrders(newOrders);
    } catch (e: any) {
      Alert.alert('Error', e.message);
    } finally {
      setSaving(false);
    }
  };

  const stockColor = (p: Product) => {
    const qty = p.stock_quantity ?? 0;
    if (qty === 0) return '#EF4444';
    if (qty <= (p.reorder_level ?? 5)) return '#F59E0B';
    return '#10B981';
  };

  return (
    <View style={{ flex: 1 }}>
      {/* Filter Row */}
      <View style={s.filterBar}>
        <TouchableOpacity
          style={[s.filterChip, showLowOnly && s.filterChipActive]}
          onPress={() => setShowLowOnly(v => !v)}
        >
          <Ionicons name="alert-circle-outline" size={12} color={showLowOnly ? '#fff' : colors.primary} />
          <Text style={[s.filterChipText, showLowOnly && s.filterChipTextActive]}>Low Stock</Text>
        </TouchableOpacity>
        <TouchableOpacity style={s.filterChip} onPress={selectLowStock}>
          <Ionicons name="checkmark-done-outline" size={12} color={colors.primary} />
          <Text style={s.filterChipText}>Auto Select Low</Text>
        </TouchableOpacity>
        <TouchableOpacity style={s.filterChip} onPress={() => setSelected({})}>
          <Text style={s.filterChipText}>Clear</Text>
        </TouchableOpacity>
      </View>

      {/* Vendor filter tabs */}
      <ScrollView horizontal showsHorizontalScrollIndicator={false} style={s.vendorScroll} contentContainerStyle={{ gap: 8, paddingHorizontal: 16 }}>
        {vendors.map(v => (
          <TouchableOpacity
            key={v}
            style={[s.vendorChip, vendorFilter === v && s.vendorChipActive]}
            onPress={() => setVendorFilter(v)}
          >
            <Text style={[s.vendorChipText, vendorFilter === v && s.vendorChipTextActive]}>{v}</Text>
          </TouchableOpacity>
        ))}
      </ScrollView>

      <FlatList
        data={filtered}
        keyExtractor={p => p.id}
        contentContainerStyle={{ padding: 16, paddingBottom: selectedProducts.length > 0 ? 160 : 40 }}
        ListEmptyComponent={
          <View style={s.empty}>
            <Ionicons name="cube-outline" size={48} color={colors.textMuted} />
            <Text style={s.emptyText}>No products found</Text>
          </View>
        }
        renderItem={({ item: p }) => {
          const isSelected = !!selected[p.id];
          const sc = stockColor(p);
          return (
            <TouchableOpacity
              style={[s.productCard, isSelected && s.productCardSelected]}
              onPress={() => toggle(p)}
              activeOpacity={0.8}
            >
              <View style={s.cardRow}>
                <View style={[s.checkbox, isSelected && s.checkboxActive]}>
                  {isSelected && <Ionicons name="checkmark" size={14} color="#fff" />}
                </View>
                <View style={{ flex: 1 }}>
                  <Text style={s.productName}>{p.name}</Text>
                  <Text style={s.productMeta}>
                    SKU: {p.sku || '—'} • {getVendor(p)}
                  </Text>
                </View>
                <View style={[s.stockBadge, { backgroundColor: sc + '20' }]}>
                  <Text style={[s.stockText, { color: sc }]}>{p.stock_quantity ?? '—'} {p.unit}</Text>
                </View>
              </View>

              <View style={s.cardInfo}>
                <Text style={s.infoLabel}>Reorder at: <Text style={s.infoVal}>{p.reorder_level ?? 5}</Text></Text>
                <Text style={s.infoLabel}>Suggested: <Text style={s.infoVal}>{suggestedQty(p)}</Text></Text>
              </View>

              {isSelected && (
                <View style={s.qtyRow}>
                  <Text style={s.qtyLabel}>Order Qty</Text>
                  <TouchableOpacity
                    style={s.qtyMinus}
                    onPress={() => {
                      const cur = parseInt(selected[p.id]?.qty || '1', 10) || 1;
                      if (cur > 1) setSelected(prev => ({ ...prev, [p.id]: { qty: String(cur - 1) } }));
                    }}
                  >
                    <Ionicons name="remove" size={16} color={colors.textPrimary} />
                  </TouchableOpacity>
                  <TextInput
                    style={s.qtyInput}
                    value={selected[p.id]?.qty}
                    onChangeText={v => setSelected(prev => ({ ...prev, [p.id]: { qty: v } }))}
                    keyboardType="number-pad"
                    placeholder="0"
                    placeholderTextColor={colors.textMuted}
                  />
                  <TouchableOpacity
                    style={s.qtyPlus}
                    onPress={() => {
                      const cur = parseInt(selected[p.id]?.qty || '0', 10) || 0;
                      setSelected(prev => ({ ...prev, [p.id]: { qty: String(cur + 1) } }));
                    }}
                  >
                    <Ionicons name="add" size={16} color="#fff" />
                  </TouchableOpacity>
                </View>
              )}
            </TouchableOpacity>
          );
        }}
      />

      {/* Bottom bar — only Place Order */}
      {selectedProducts.length > 0 && (
        <View style={s.bottomBar}>
          <View style={s.bottomInfo}>
            <Text style={s.bottomCount}>{selectedProducts.length} product{selectedProducts.length !== 1 ? 's' : ''}</Text>
            <Text style={s.bottomVendors}>
              {Object.keys(vendorGroups).map(v => v).join(' · ')}
            </Text>
          </View>
          <TouchableOpacity style={s.placeBtn} onPress={handlePlaceOrders} disabled={saving}>
            {saving ? (
              <ActivityIndicator color="#fff" size="small" />
            ) : (
              <>
                <Ionicons name="cart" size={16} color="#fff" />
                <Text style={s.placeBtnText}>Place Order</Text>
              </>
            )}
          </TouchableOpacity>
        </View>
      )}

      {/* Success modal shown after order is placed */}
      {createdOrders.length > 0 && (
        <OrderSuccessModal
          orders={createdOrders}
          companyName={company?.company_name || 'Company'}
          onDone={() => {
            setCreatedOrders([]);
            onOrderCreated();
          }}
        />
      )}
    </View>
  );
};

const styles = (colors: any) => StyleSheet.create({
  filterBar: { flexDirection: 'row', gap: 8, paddingHorizontal: 16, paddingVertical: 10, flexWrap: 'wrap' },
  filterChip: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 6, borderRadius: Radius.full, borderWidth: 1, borderColor: colors.primary + '60', backgroundColor: colors.surfaceAlt },
  filterChipActive: { backgroundColor: colors.primary },
  filterChipText: { fontSize: 11, fontWeight: '700', color: colors.primary },
  filterChipTextActive: { color: '#fff' },
  vendorScroll: { maxHeight: 44, marginBottom: 4 },
  vendorChip: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: Radius.full, backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: colors.border },
  vendorChipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  vendorChipText: { fontSize: 12, fontWeight: '600', color: colors.textSecondary },
  vendorChipTextActive: { color: '#fff' },
  productCard: { backgroundColor: colors.surface, borderRadius: Radius.lg, padding: 14, marginBottom: 10, ...Shadow.sm, borderWidth: 1.5, borderColor: 'transparent' },
  productCardSelected: { borderColor: colors.primary },
  cardRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  checkbox: { width: 22, height: 22, borderRadius: 6, borderWidth: 2, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' },
  checkboxActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  productName: { fontSize: 14, fontWeight: '700', color: colors.textPrimary },
  productMeta: { fontSize: 11, color: colors.textMuted, marginTop: 2 },
  stockBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: Radius.full },
  stockText: { fontSize: 12, fontWeight: '700' },
  cardInfo: { flexDirection: 'row', gap: 16, marginTop: 8, marginLeft: 32 },
  infoLabel: { fontSize: 11, color: colors.textSecondary, fontWeight: '500' },
  infoVal: { fontWeight: '700', color: colors.textPrimary },
  qtyRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 10, marginLeft: 32 },
  qtyLabel: { fontSize: 12, fontWeight: '600', color: colors.textSecondary, flex: 1 },
  qtyMinus: { width: 32, height: 32, borderRadius: 8, borderWidth: 1.5, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' },
  qtyInput: { borderWidth: 1.5, borderColor: colors.primary, borderRadius: Radius.md, paddingHorizontal: 10, paddingVertical: 6, fontSize: 16, fontWeight: '800', color: colors.textPrimary, minWidth: 60, textAlign: 'center' },
  qtyPlus: { width: 32, height: 32, borderRadius: 8, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' },
  empty: { alignItems: 'center', paddingTop: 60, gap: 10 },
  emptyText: { fontSize: 15, fontWeight: '600', color: colors.textMuted },
  bottomBar: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: colors.surface, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 12, ...Shadow.md, borderTopWidth: 1, borderColor: colors.border },
  bottomInfo: { flex: 1 },
  bottomCount: { fontSize: 14, fontWeight: '800', color: colors.textPrimary },
  bottomVendors: { fontSize: 11, color: colors.textMuted, marginTop: 2 },
  placeBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: colors.primary, paddingVertical: 12, paddingHorizontal: 20, borderRadius: Radius.full },
  placeBtnText: { fontSize: 14, fontWeight: '700', color: '#fff' },
  // Success modal
  successModal: { flex: 1, backgroundColor: colors.background },
  successTop: { alignItems: 'center', paddingTop: 60, paddingBottom: 24, paddingHorizontal: 24 },
  successIcon: { marginBottom: 12 },
  successTitle: { fontSize: 26, fontWeight: '800', color: colors.textPrimary, marginBottom: 6 },
  successSubtitle: { fontSize: 14, color: colors.textSecondary, textAlign: 'center' },
  successBody: { padding: 20 },
  successSectionLabel: { fontSize: 11, fontWeight: '700', color: colors.textSecondary, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 12 },
  orderPdfCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, borderRadius: Radius.lg, padding: 14, marginBottom: 10, ...Shadow.sm },
  orderPdfNum: { fontSize: 13, fontWeight: '800', color: colors.textPrimary },
  orderPdfVendor: { fontSize: 12, color: colors.textSecondary, marginTop: 2 },
  orderPdfItems: { fontSize: 11, color: colors.textMuted, marginTop: 2 },
  sharePdfBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: colors.primary, paddingVertical: 10, paddingHorizontal: 14, borderRadius: Radius.full },
  sharePdfBtnText: { fontSize: 12, fontWeight: '700', color: '#fff' },
  successFooter: { padding: 20 },
  doneBtn: { backgroundColor: colors.primary, borderRadius: Radius.full, paddingVertical: 15, alignItems: 'center' },
  doneBtnText: { fontSize: 15, fontWeight: '700', color: '#fff' },
});
